force-app/main/default/objects/Commentary__c/Commentary__c.object-meta.xml
<CustomObject>
    <description>Stores match commentary summary and full event JSON</description>
    <label>Commentary</label>
    <nameField>
        <displayFormat>COM-{0000}</displayFormat>
        <label>Commentary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commentaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Represents a match/game event across all sports</description>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match_Moment__c/Match_Moment__c.object-meta.xml
<CustomObject>
    <description>Normalized major events for querying (goals, cards, critical moments only)</description>
    <label>Match Moment</label>
    <nameField>
        <displayFormat>EVT-{00000}</displayFormat>
        <label>Match Moment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Match Moments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match_Moment__c/fields/Commentary__c.field-meta.xml
<CustomField>
    <fullName>Commentary__c</fullName>
    <label>Commentary</label>
    <referenceTo>Commentary__c</referenceTo>
    <relationshipLabel>Match Moments</relationshipLabel>
    <relationshipName>Match_Moments</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/Event_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Time__c</fullName>
    <label>Event Time</label>
    <type>DateTime</type>
    <description>The time when the event occurred</description>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/Is_Shareable__c.field-meta.xml
<CustomField>
    <fullName>Is_Shareable__c</fullName>
    <label>Is Shareable</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
    <description>Indicates if this event can be shared publicly</description>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Match Moments</relationshipLabel>
    <relationshipName>Match_Moments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/Public_URL__c.field-meta.xml
<CustomField>
    <fullName>Public_URL__c</fullName>
    <label>Public URL</label>
    <type>Text</type>
    <length>255</length>
    <description>Shareable public URL for this moment</description>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/View_Count__c.field-meta.xml
<CustomField>
    <fullName>View_Count__c</fullName>
    <label>View Count</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
    <defaultValue>0</defaultValue>
    <description>Total number of times this event has been viewed</description>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/Viral_Score__c.field-meta.xml
<CustomField>
    <fullName>Viral_Score__c</fullName>
    <label>Viral Score</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>2</scale>
    <defaultValue>0</defaultValue>
    <description>Weighted viral engagement score</description>
</CustomField>

force-app/main/default/classes/selectors/MatchMomentsSelector.cls
/**
 * @description Selector for Match_Moment__c
 * @author Brendan Milton
 * @date 2025-12-05
 */
public inherited sharing class MatchMomentsSelector extends fflib_SObjectSelector {
    
    public static MatchMomentsSelector newInstance() {
        return (MatchMomentsSelector) Application.Selector.newInstance(Match_Moment__c.SObjectType);
    }
    
    public Schema.SObjectType getSObjectType() {
        return Match_Moment__c.SObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Match_Moment__c.Id,
            Match_Moment__c.Name,
            Match_Moment__c.Commentary__c,
            Match_Moment__c.Event_Type__c,
            Match_Moment__c.Event_Time__c,
            Match_Moment__c.Is_Shareable__c,
            Match_Moment__c.Public_URL__c,
            Match_Moment__c.Share_Count__c,
            Match_Moment__c.View_Count__c,
            Match_Moment__c.Viral_Score__c
        };
    }
    
    public List<Match_Moment__c> selectById(Set<Id> ids) {
        return (List<Match_Moment__c>) selectSObjectsById(ids);
    }
    
    public List<Match_Moment__c> selectShareableByFixture(Set<Id> fixtureIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Commentary__r.Match__c IN :fixtureIds AND Is_Shareable__c = true')
            .setOrdering('Event_Time__c', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Match_Moment__c>) Database.query(query.toSOQL());
    }
}