force-app/main/default/objects/Social_Engagement__c/Social_Engagement__c.object-meta.xml
<CustomObject>
    <description>Track all social sharing and engagement for moments</description>
    <label>Social Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
        <displayFormat>SE-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Social Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <required>true</required>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Share</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
            <value>
                <fullName>Like</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Click</fullName>
            </value>
            <value>
                <fullName>Embed_View</fullName>
                <label>Embed View</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <description>Type of engagement action</description>
</CustomField>

force-app/main/default/objects/Social_Engagement__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <required>true</required>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Reddit</fullName>
            </value>
            <value>
                <fullName>TikTok</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <default>true</default>
                <label>Website</label>
            </value>
            <value>
                <fullName>Mobile_App</fullName>
                <label>Mobile App</label>
            </value>
            <value>
                <fullName>Link_Copy</fullName>
                <label>Link Copy</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <description>Platform where engagement occurred</description>
</CustomField>

force-app/main/default/classes/domains/SocialEngagements.cls
/**
 * @description Domain class for Social_Engagement__c
 * @author Brendan Milton
 * @date 2025-12-05
 */
public inherited sharing class SocialEngagements extends fflib_SObjectDomain implements ISocialEngagements {
    
    public static final String TYPE_SHARE = 'Share';
    public static final String TYPE_VIEW = 'View';
    public static final String TYPE_CLICK = 'Click';
    
    public static final String PLATFORM_TWITTER = 'Twitter';
    public static final String PLATFORM_FACEBOOK = 'Facebook';
    public static final String PLATFORM_WHATSAPP = 'WhatsApp';
    public static final String PLATFORM_LINKEDIN = 'LinkedIn';
    
    public SocialEngagements(List<Social_Engagement__c> records) {
        super(records);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> records) {
            return new SocialEngagements((List<Social_Engagement__c>) records);
        }
    }
    
    public static ISocialEngagements newInstance(List<Social_Engagement__c> records) {
        return (ISocialEngagements) Application.Domain.newInstance(records);
    }
    
    public List<Social_Engagement__c> getEngagements() {
        return (List<Social_Engagement__c>) getRecords();
    }
    
    public void setEngagementType(String engagementType) {
        for (Social_Engagement__c engagement : getEngagements()) {
            engagement.Engagement_Type__c = engagementType;
        }
    }
    
    public void setPlatform(String platform) {
        for (Social_Engagement__c engagement : getEngagements()) {
            engagement.Platform__c = platform;
        }
    }
}