force-app/main/default/objects/Lineup__c/Lineup__c.object-meta.xml
<CustomObject>
    <label>Lineup</label>
    <nameField>
        <label>Lineup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lineups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lineup__c/fields/Captain__c.field-meta.xml
<CustomField>
    <fullName>Captain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team captain for this match</description>
    <label>Captain</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lineups (Captain)</relationshipLabel>
    <relationshipName>Lineups_Captain</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lineup__c/fields/Formation__c.field-meta.xml
<CustomField>
    <fullName>Formation__c</fullName>
    <description>Extracted formation (4-3-3, 4-4-2)</description>
    <label>Formation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lineup__c/fields/Lineup_JSON__c.field-meta.xml
<CustomField>
    <fullName>Lineup_JSON__c</fullName>
    <description>JSON representation of the lineup including players, positions, and bench</description>
    <label>Lineup JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lineup__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Lineups</relationshipLabel>
    <relationshipName>Lineups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lineup__c/fields/Starting_XI_Count__c.field-meta.xml
<CustomField>
    <fullName>Starting_XI_Count__c</fullName>
    <description>Count of starting players</description>
    <label>Starting XI Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lineup__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lineups</relationshipLabel>
    <relationshipName>Lineups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Represents a match/game event across all sports</description>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/selectors/LineupsSelector.cls
/**
 * @description Selector for Lineup__c
 * @author Brendan Milton
 * @date 2025-12-31
 */
public inherited sharing class LineupsSelector extends fflib_SObjectSelector {
    
    public static LineupsSelector newInstance() {
        return (LineupsSelector) Application.Selector.newInstance(Lineup__c.SObjectType);
    }
    
    public Schema.SObjectType getSObjectType() {
        return Lineup__c.SObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Lineup__c.Id,
            Lineup__c.Name,
            Lineup__c.Match__c,
            Lineup__c.Team__c,
            Lineup__c.Formation__c,
            Lineup__c.Starting_XI_Count__c,
            Lineup__c.Captain__c,
            Lineup__c.Lineup_JSON__c
        };
    }
    
    public List<Lineup__c> selectById(Set<Id> ids) {
        return (List<Lineup__c>) selectSObjectsById(ids);
    }
    
    /**
     * @description Select lineups by match IDs
     * @param matchIds Set of Match__c record IDs
     * @return List of Lineup__c records
     */
    public List<Lineup__c> selectByMatchIds(Set<Id> matchIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Match__c IN :matchIds');
        return (List<Lineup__c>) Database.query(query.toSOQL());
    }
    
    /**
     * @description Select lineups by match and team IDs
     * @param matchIds Set of Match__c record IDs
     * @param teamIds Set of Account (Team) record IDs
     * @return Map of Match__c Id -> Team__c Id -> Lineup__c
     */
    public Map<Id, Map<Id, Lineup__c>> selectByMatchAndTeamIds(Set<Id> matchIds, Set<Id> teamIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Match__c IN :matchIds AND Team__c IN :teamIds');
        
        List<Lineup__c> lineups = (List<Lineup__c>) Database.query(query.toSOQL());
        
        Map<Id, Map<Id, Lineup__c>> result = new Map<Id, Map<Id, Lineup__c>>();
        for (Lineup__c lineup : lineups) {
            if (!result.containsKey(lineup.Match__c)) {
                result.put(lineup.Match__c, new Map<Id, Lineup__c>());
            }
            result.get(lineup.Match__c).put(lineup.Team__c, lineup);
        }
        
        return result;
    }
}