force-app/main/default/objects/Match_Moment__c/Match_Moment__c.object-meta.xml
<CustomObject>
    <description>Normalized major events for querying (goals, cards, critical moments only)</description>
    <label>Match Moment</label>
    <nameField>
        <displayFormat>EVT-{00000}</displayFormat>
        <label>Match Moment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Match Moments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match_Moment__c/fields/Is_Shareable__c.field-meta.xml
<CustomField>
    <fullName>Is_Shareable__c</fullName>
    <label>Is Shareable</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
    <description>Indicates if this event can be shared publicly</description>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/View_Count__c.field-meta.xml
<CustomField>
    <fullName>View_Count__c</fullName>
    <label>View Count</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
    <defaultValue>0</defaultValue>
    <description>Total number of times this event has been viewed</description>
</CustomField>

force-app/main/default/objects/Match_Moment__c/fields/Viral_Score__c.field-meta.xml
<CustomField>
    <fullName>Viral_Score__c</fullName>
    <label>Viral Score</label>
    <type>Number</type>
    <precision>10</precision>
    <scale>2</scale>
    <defaultValue>0</defaultValue>
    <description>Weighted viral engagement score</description>
</CustomField>

force-app/main/default/classes/domains/MatchMoments.cls
/**
 * @description Domain class for Match_Moment__c
 * @author Brendan Milton
 * @date 2025-12-05
 */
public inherited sharing class MatchMoments extends fflib_SObjectDomain implements IMatchMoments {
    
    public MatchMoments(List<Match_Moment__c> records) {
        super(records);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> records) {
            return new MatchMoments((List<Match_Moment__c>) records);
        }
    }
    
    public static IMatchMoments newInstance(List<Match_Moment__c> records) {
        return (IMatchMoments) Application.Domain.newInstance(records);
    }
    
    public List<Match_Moment__c> getEvents() {
        return (List<Match_Moment__c>) getRecords();
    }
    
    public void makeShareable() {
        for (Match_Moment__c event : getEvents()) {
            event.Is_Shareable__c = true;
        }
    }
    
    public void updateViralScore(Decimal score) {
        for (Match_Moment__c event : getEvents()) {
            event.Viral_Score__c = score;
        }
    }
    
    public void incrementShareCount() {
        for (Match_Moment__c event : getEvents()) {
            event.Share_Count__c = (event.Share_Count__c != null ? event.Share_Count__c : 0) + 1;
        }
    }
    
    public void incrementViewCount() {
        for (Match_Moment__c event : getEvents()) {
            event.View_Count__c = (event.View_Count__c != null ? event.View_Count__c : 0) + 1;
        }
    }
}