force-app/main/default/objects/Account/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <description>Team abbreviation (e.g., "ARS" for Arsenal, "LAL" for Lakers)</description>
    <label>Abbreviation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Current_League_Rank__c.field-meta.xml
<CustomField>
    <fullName>Current_League_Rank__c</fullName>
    <description>Dynamic ranking (requires frequent updates)</description>
    <label>Current League Rank</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ESPN_ID__c.field-meta.xml
<CustomField>
    <fullName>ESPN_ID__c</fullName>
    <description>The anchor for upserts from ESPN API. Universal field name for all sports.</description>
    <externalId>true</externalId>
    <label>ESPN ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ESPN_Team_ID__c.field-meta.xml
<CustomField>
    <fullName>ESPN_Team_ID__c</fullName>
    <externalId>true</externalId>
    <label>ESPN Team ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Founded_Year__c.field-meta.xml
<CustomField>
    <fullName>Founded_Year__c</fullName>
    <label>Founded Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Logo_Url__c.field-meta.xml
<CustomField>
    <fullName>Logo_Url__c</fullName>
    <description>Link to the CDN image (universal field name replacing Team_Logo_URL__c)</description>
    <label>Logo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sport__c.field-meta.xml
<CustomField>
    <fullName>Sport__c</fullName>
    <description>Sport type for ESPN API calls</description>
    <label>Sport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soccer</fullName>
            </value>
            <value>
                <fullName>Basketball</fullName>
            </value>
            <value>
                <fullName>Cricket</fullName>
            </value>
            <value>
                <fullName>Rugby</fullName>
            </value>
            <value>
                <fullName>AFL</fullName>
            </value>
            <value>
                <fullName>NFL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stadium_Name__c.field-meta.xml
<CustomField>
    <fullName>Stadium_Name__c</fullName>
    <label>Stadium Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Team_Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Team_Primary_Color__c</fullName>
    <label>Team Primary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Team_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Short_Name__c</fullName>
    <label>Team Short Name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Venue_Name__c.field-meta.xml
<CustomField>
    <fullName>Venue_Name__c</fullName>
    <description>Stadium/Arena name (universal field name replacing Stadium_Name__c)</description>
    <label>Venue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/TeamsSelector.cls
/**
 * @description Selector implementation for Account (Teams)
 * Filters to Type = 'Team' records only
 * @author Brendan Milton
 * @date 2025-12-05
 */
public inherited sharing class TeamsSelector extends fflib_SObjectSelector implements ITeamsSelector {
    
    public static ITeamsSelector newInstance() {
        return (ITeamsSelector) Application.Selector.newInstance(Account.SObjectType);
    }
    
    public Schema.SObjectType getSObjectType() {
        return Account.SObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Account.Id,
            Account.Name,
            Account.Type,
            Account.Sport__c,
            Account.ESPN_ID__c,
            Account.ESPN_Team_ID__c,
            Account.Abbreviation__c,
            Account.Logo_Url__c,
            Account.Venue_Name__c,
            Account.Team_Short_Name__c,
            Account.Team_Primary_Color__c,
            Account.Stadium_Name__c,
            Account.Founded_Year__c,
            Account.Current_League_Rank__c
        };
    }
    
    public List<Account> selectById(Set<Id> accountIds) {
        return (List<Account>) selectSObjectsById(accountIds);
    }
    
    public List<Account> selectByESPNTeamIds(Set<String> espnTeamIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('ESPN_Team_ID__c IN :espnTeamIds AND Type = \'Team\'');
        return (List<Account>) Database.query(query.toSOQL());
    }
    
    public List<Account> selectBySport(String sport) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Sport__c = :sport AND Type = \'Team\'')
            .setOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Account>) Database.query(query.toSOQL());
    }
    
    public List<Account> selectTeamsWithType() {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Type = \'Team\'')
            .setOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING);
        return (List<Account>) Database.query(query.toSOQL());
    }
    
    /**
     * @description Build a map of ESPN Team ID to Salesforce Account ID
     * Useful for bulk operations when linking fixtures to teams
     * @param espnTeamIds Set of ESPN Team ID strings
     * @return Map of ESPN Team ID to Salesforce Account ID
     */
    public Map<String, Id> selectESPNIdToAccountIdMap(Set<String> espnTeamIds) {
        Map<String, Id> resultMap = new Map<String, Id>();
        
        List<Account> teams = selectByESPNTeamIds(espnTeamIds);
        for (Account team : teams) {
            if (String.isNotBlank(team.ESPN_Team_ID__c)) {
                resultMap.put(team.ESPN_Team_ID__c, team.Id);
            }
        }
        
        return resultMap;
    }
}