force-app/main/default/objects/Commentary_Event__c/Commentary_Event__c.object-meta.xml
<CustomObject>
    <description>Normalized major events for querying (goals, cards, critical moments only)</description>
    <label>Commentary Event</label>
    <nameField>
        <displayFormat>EVT-{00000}</displayFormat>
        <label>Commentary Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commentary Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Engagement__c/Social_Engagement__c.object-meta.xml
<CustomObject>
    <description>Track all social sharing and engagement for moments</description>
    <label>Social Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>AutoNumber</type>
        <displayFormat>SE-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Social Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Engagement__c/fields/Commentary_Event__c.field-meta.xml
<CustomField>
    <fullName>Commentary_Event__c</fullName>
    <label>Commentary Event</label>
    <type>Lookup</type>
    <referenceTo>Commentary_Event__c</referenceTo>
    <relationshipLabel>Social Engagements</relationshipLabel>
    <relationshipName>Social_Engagements</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/Social_Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <required>true</required>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Share</fullName>
            </value>
            <value>
                <fullName>View</fullName>
            </value>
            <value>
                <fullName>Like</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Click</fullName>
            </value>
            <value>
                <fullName>Embed_View</fullName>
                <label>Embed View</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <description>Type of engagement action</description>
</CustomField>

force-app/main/default/objects/Social_Engagement__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <required>true</required>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Reddit</fullName>
            </value>
            <value>
                <fullName>TikTok</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <default>true</default>
                <label>Website</label>
            </value>
            <value>
                <fullName>Mobile_App</fullName>
                <label>Mobile App</label>
            </value>
            <value>
                <fullName>Link_Copy</fullName>
                <label>Link Copy</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <description>Platform where engagement occurred</description>
</CustomField>

force-app/main/default/classes/selectors/SocialEngagementsSelector.cls
/**
 * @description Selector for Social_Engagement__c
 * @author Brendan Milton
 * @date 2025-12-05
 */
public inherited sharing class SocialEngagementsSelector extends fflib_SObjectSelector {
    
    public Schema.SObjectType getSObjectType() {
        return Social_Engagement__c.SObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Social_Engagement__c.Id,
            Social_Engagement__c.Name,
            Social_Engagement__c.Commentary_Event__c,
            Social_Engagement__c.Platform__c,
            Social_Engagement__c.Engagement_Type__c
        };
    }
    
    public List<Social_Engagement__c> selectById(Set<Id> ids) {
        return (List<Social_Engagement__c>) selectSObjectsById(ids);
    }
}