force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Represents a match/game event across all sports</description>
    <label>Match</label>
    <nameField>
        <displayFormat>MATCH-{00000}</displayFormat>
        <label>Match Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match_Participation__c/Match_Participation__c.object-meta.xml
<CustomObject>
    <description>Junction object linking people to fixtures (replaces OpportunityContactRole)</description>
    <label>Match Participation</label>
    <nameField>
        <displayFormat>FP-{00000}</displayFormat>
        <label>Match Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Match Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match_Participation__c/fields/Match__c.field-meta.xml
<CustomField>
    <fullName>Match__c</fullName>
    <label>Match</label>
    <referenceTo>Match__c</referenceTo>
    <relationshipLabel>Match Participations</relationshipLabel>
    <relationshipName>Match_Participations</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match_Participation__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Match Participations (Player)</relationshipLabel>
    <relationshipName>Match_Participations_Player</relationshipName>
    <description>The player who participated in this fixture</description>
</CustomField>

force-app/main/default/objects/Match_Participation__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Match Participations</relationshipLabel>
    <relationshipName>Match_Participations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selectors/MatchParticipationsSelector.cls
/**
 * @description Selector for Match_Participation__c
 * @author Brendan Milton
 * @date 2025-12-05
 */
public inherited sharing class MatchParticipationsSelector extends fflib_SObjectSelector {
    
    public static MatchParticipationsSelector newInstance() {
        return (MatchParticipationsSelector) Application.Selector.newInstance(Match_Participation__c.SObjectType);
    }
    
    public Schema.SObjectType getSObjectType() {
        return Match_Participation__c.SObjectType;
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Match_Participation__c.Id,
            Match_Participation__c.Name,
            Match_Participation__c.Match__c,
            Match_Participation__c.Player__c,
            Match_Participation__c.Team__c
        };
    }
    
    public List<Match_Participation__c> selectById(Set<Id> ids) {
        return (List<Match_Participation__c>) selectSObjectsById(ids);
    }
    
    /**
     * @description Select participations by match IDs
     * @param matchIds Set of Match__c record IDs
     * @return List of Match_Participation__c records
     */
    public List<Match_Participation__c> selectByMatchIds(Set<Id> matchIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Match__c IN :matchIds');
        return (List<Match_Participation__c>) Database.query(query.toSOQL());
    }
    
    /**
     * @description Select participations by match and team IDs
     * @param matchIds Set of Match__c record IDs
     * @param teamIds Set of Account (Team) record IDs
     * @return List of Match_Participation__c records
     */
    public List<Match_Participation__c> selectByMatchAndTeamIds(Set<Id> matchIds, Set<Id> teamIds) {
        fflib_QueryFactory query = newQueryFactory()
            .setCondition('Match__c IN :matchIds AND Team__c IN :teamIds');
        return (List<Match_Participation__c>) Database.query(query.toSOQL());
    }
}